/* requiring dependencies */
import { backendStatus } from "../types";

// application state
type state = {

    // base
    // socket: Socket
    theme: "dark" | "light" | "auto"
    themeError: string
    unMount: any,
    loading: boolean
    authenticated: boolean
    disabled: boolean
    all: any
    id: string
    ids: string[]
    edit: boolean
    notification: string
    searchKeyword: string
    schema: keyof state
    collection: keyof state
    backendStatus: backendStatus
    files: any
    file: any
    filesError: string
    selected: string[]
    propsCondition: object
    select: any
    joinForeignKeys: boolean
    fields: string[]
    onlineUsers: string[]
    description: string
    descriptionError: string
    date: string
    dateError: string
    totalAmount: string
    totalAmountError: string
    paidAmount: string
    paidAmountError: string
    location: string
    locationError: string
    tin: string
    tinError: string
    status: string
    statusError: string
    orderNumber: number
    type: string
    typeError: string
    language: "english" | "swahili"
    languageError: string
    systemLoading: "yes" | "no"
    systemLoadingError: string

    // user
    account: any
    accountError: string
    password: string
    passwordError: string
    oldPassword: string
    oldPasswordError: string
    code: string
    codeError: string
    passwordConfirmation: string
    passwordConfirmationError: string
    userName: string
    userNameError: string
    phoneNumber: string
    phoneNumberError: string
    extraPhoneNumber: string
    extraPhoneNumberError: string
    fullName: string
    fullNameError: string
    accountType: string
    accountTypeError: string
    twoFactorAuthenticationEnabled: "true" | "false"
    users: any[]
    user: any
    oldPhoneNumber: string
    phoneNumberVerified: boolean
    apiKey: string
    apiKeyError: string

    // listing
    page: number
    pages: number
    limit: number
    nextPage: number
    previousPage: number
    sort: string
    order: 1 | -1
    condition: string
    limits: number[]
    pageNumbers: number[]
    list: any[]

    // product
    productName: string
    productNameError: string
    buyingPrice: string
    buyingPriceError: string
    sellingPrice: string
    sellingPriceError: string
    reorderStockLevel: string
    reorderStockLevelError: string
    stock: string
    stockError: string
    quantity: string
    quantityError: string
    products: any[]
    product: any
    productId: string

    // activity
    activities: any[]
    activity: any

    // branch
    branches: any[]
    branch: any

    // customer
    customers: any[]
    customer: any
    customerName: string
    customerNameError: string
    customerId: string

    //debt
    debts: any[]
    debt: any
    debt_histories: any[]
    debt_history: any
    debtType: string
    debtTypeError: string

    // device
    devices: any[]
    device: any

    // expense
    expenses: any[]
    expense: any
    expense_types: any[]
    expense_type: any
    expense_typeName: string
    expense_typeNameError: string
    expenseName: string
    expenseNameError: string

    // order
    orders: any[]
    // order: any

    // payment
    payments: any[]
    payment: any

    // purchase
    purchases: any[]
    purchase: any

    // role
    roles: any[]
    role: any

    // sales
    sales: any[]
    sale: any
    pos: "cart" | "invoice" | "order"

    // service
    services: any[]
    service: any

    // store
    stores: any[]
    store: any
    store_products: any[]
    store_product: any

    name: string
    nameError: string
    region: string
    regionError: string
    street: string
    streetError: string
    vendor: string
    vendorError: string
    fee: string
    feeError: string
    image: string
    imageError: string
    oldImage: string
    oldImageError: string
    permissions: string[]
    permissionsError: string
    report: any
    message: any
    proforma_invoice: any
    branchIdError: string
    roleId: string
    roleIdError: string
    paymentType: string
    paymentTypeError: string
    branchId: string
    messages: any[]
    receivers: string
    receiversError: string
    costPerMessage: number
    messageCost: number
    branchName: string
    branchNameError: string
    title: string
    storeId: string
    storeIdError: string
    store_product_id: string
    pathname: string
    adjustment: any
    adjustmentError: string
    adjustments: any[]
    balance: string
    balanceError: string
    reportType: string
    reportTypeError: string
    viewDeletedReport: "yes" | "no"
    dateTo: string
    dateToError: string
    customerIdError: string
    expense_typeId: string
    expense_typeIdError: string
    storeProductId: string
    storeProductIdError: string
    productIdError: string
    userId: string
    userIdError: string
    year: number
    yearError: string
    notifications: string[]
    saleNote: string
    saleNoteError: string
    invoiceNote: string
    invoiceNoteError: string
    closingTime: string
    closingTimeError: string
    openingTime: string
    openingTimeError: string
    paymentMethods: any[]
    email: string
    emailError: string
    website: string
    websiteError: string
    pobox: string
    poboxError: string
    customer_debt: any
    shop_debt: any
    currencyFormat: string
    currencyFormatError: string
    cashSales: number
    creditSales: number
    customerPaidDebts: number
    customerPartialPaidDebts: number
    customerUnpaidDebts: number
    revenue: number
    purchaseCost: number
    freight: number
    cogs: number
    grossProfit: number
    totalPayments: number
    paidExpenses: number
    partialPaidExpenses: number
    unpaidExpenses: number
    shopPaidDebts: number
    shopPartialPaidDebts: number
    shopUnpaidDebts: number
    totalExpenses: number
    netIncome: number
    supplier: any,
    supplierName: string
    supplierNameError: string
    suppliers: any[]
    supplierId: string
    supplierIdError: string
    invoiceNumber: string
    invoiceNumberError: string
    customer_count: any
    customer_counts: any[]
    route: any
    routes: any[]
    routeId: string
    routeIdError: string
    truck: any
    trucks: any[]
    truckId: string
    truckIdError: string
    truck_order: any
    truck_orders: any[]
    truckOrderId: string
    truckOrderIdError: string
    from: string
    fromError: string
    to: string
    toError: string
    distance: string
    distanceError: string
    cost: string
    costError: string
    plateNumber: string
    plateNumberError: string
    statusBefore: string
    statusBeforeError: string
    statusAfter: string
    statusAfterError: string
    paidOrders: number
    unpaidOrders: number
    partialPaidOrders: number
    barcode: string
    barcodeError: string
    cargo: any
    cargos: any[]
    cargoId: string
    cargoIdError: string
    paidCargos: number
    unpaidCargos: number
    partialPaidCargos: number
    offset: number
    visibleData: any[]
    stocks: any[]
    days: string
    daysError: string
    deviceName: string
    deviceNameError: string
    deviceId: string
    deviceIdError: string
    brand: string
    brandError: string
    model: string
    modelError: string
    imei: string
    imeiError: string
    key: string
    keyError: string
    value: string
    valueError: string
    features: { key: string, value: string }[]
    serviceName: string
    serviceNameError: string
    serviceCost: string
    serviceCostError: string
    productCost: string
    productCostError: string
    completedServices: number
    incompleteServices: number
    freightName: string
    freightNameError: string
    freights: any[]
    paidFreights: number
    unpaidFreights: number
    partialPaidFreights: number
    darkColor: string
    lightColor: string
    storeName: string
    storeNameError: string
    routeName: string
    routeNameError: string
    truckName: string
    truckNameError: string
    roleName: string
    roleNameError: string
    accountNumber: string
    accountNumberError: string
    provider: string
    providerError: string
    accounts: any[]
    reference: string
    referenceError: string
    accountData: any
    transaction: any
    transactions: any[]
    secondAccount: string
    secondAccountError: string
    secondAccounts: any[]
    secondAccountData: any
    isStoreProduct: boolean
    useSupplierAccount: "yes" | "no"
    useCustomerAccount: "yes" | "no"
    hotelName: string
    hotelNameError: string
    hotelCategory: string
    hotelCategoryError: string
    hotelRooms: { price: string, type: string }[]
    hotelRoomPrice: string
    hotelRoomPriceError: string
    hotelRoomType: string
    hotelRoomTypeError: string
    hotels: any[]
    hotel: any
    hotelId: string
    attractionId: string
    attractionName: string
    attractionNameError: string
    attractionCategory: string
    attractionCategoryError: string
    attraction: any
    attractions: any[]
    childFee: string
    childFeeError: string
    driverAndCarFee: string
    driverAndCarFeeError: string
    price: string
    priceError: string
    isMandatory: "yes" | "no"
    item: any
    items: any[]
    attraction_activity: any
    attraction_activities: any[]
    attractionActivityName: string
    attractionActivityNameError: string
    margin: string
    marginError: string
    adultPopulation: string
    adultPopulationError: string
    adultPopulationDays: string
    adultPopulationDaysError: string
    adultPopulationTotal: string
    adultPopulationTotalError: string
    childPopulation: string
    childPopulationError: string
    childPopulationDays: string
    childPopulationDaysError: string
    childPopulationTotal: string
    childPopulationTotalError: string
    driverPopulation: string
    driverPopulationError: string
    driverPopulationDays: string
    driverPopulationDaysError: string
    driverPopulationTotal: string
    driverPopulationTotalError: string
    admissionTotal: string
    accomodationTotal: string
    itemCount: string
    itemDays: string
    itemTotal: string
    numberOfPeople: string
    numberOfPeopleError: string
    childCostPercentage: string
    childCostPercentageError: string
    deposit: string
    depositError: string
    totalMargin: string
    quotations: any[]
    quotation: any
    trips: any[]
    quotationNumber: string
    quotationNumberError: string
    quotationId: string
    quotation_invoices: any[]
    quotation_invoice: any
    country: string
    countryError: string
    phoneCode: string
    phoneCodeError: string
    identificationNumber: string
    identificationNumberError: string
    vendors: any[]
    paidInvoice: number
    unpaidInvoice: number
    discount: number
    hasReceipt: "yes" | "no"
    eastAfricaPrice: string
    eastAfricaPriceError: string
    nonResidentPrice: string
    nonResidentPriceError: string
    expatriatePrice: string
    expatriatePriceError: string
    category: any
    categories: any[]
    categoryName: string
    categoryNameError: string
    categoryId: string
    season: string
    seasonError: string
    profit: string
    profitError: string
    primaryColor: string
    primaryColorError: string
    fontFamily: string
    fontFamilyError: string
    cif: string
    cifError: string
    priceInTZS: string
    priceInTZSError: string
    position: string
    positionError: string
    oldStock: number
    isPos: boolean
    barcodeValue: any
    request: any
    requests: any[]
    saleLimit: string
    saleLimitError: string
    purchaseLimit: string
    purchaseLimitError: string
    productCode: string
    productCodeError: string
    debtLimit: string
    debtLimitError: string
    loadTRAReceipt: "yes" | "no"
    traItemName: string
    traItemNameError: string
}

// exporting state type
export default state