import { country } from "../types";

const countries: country[] = [
    // Africa
    { name: "Algeria", phoneCode: "213", continent: "Africa" },
    { name: "Angola", phoneCode: "244", continent: "Africa" },
    { name: "Benin", phoneCode: "229", continent: "Africa" },
    { name: "Botswana", phoneCode: "267", continent: "Africa" },
    { name: "Burkina Faso", phoneCode: "226", continent: "Africa" },
    { name: "Burundi", phoneCode: "257", continent: "Africa" },
    { name: "Cabo Verde", phoneCode: "238", continent: "Africa" },
    { name: "Cameroon", phoneCode: "237", continent: "Africa" },
    { name: "Central African Republic", phoneCode: "236", continent: "Africa" },
    { name: "Chad", phoneCode: "235", continent: "Africa" },
    { name: "Comoros", phoneCode: "269", continent: "Africa" },
    { name: "Republic of the Congo", phoneCode: "242", continent: "Africa" },
    { name: "Democratic Republic of the Congo", phoneCode: "243", continent: "Africa" },
    { name: "Djibouti", phoneCode: "253", continent: "Africa" },
    { name: "Egypt", phoneCode: "20", continent: "Africa" },
    { name: "Equatorial Guinea", phoneCode: "240", continent: "Africa" },
    { name: "Eritrea", phoneCode: "291", continent: "Africa" },
    { name: "Eswatini (formerly Swaziland)", phoneCode: "268", continent: "Africa" },
    { name: "Ethiopia", phoneCode: "251", continent: "Africa" },
    { name: "Gabon", phoneCode: "241", continent: "Africa" },
    { name: "Gambia", phoneCode: "220", continent: "Africa" },
    { name: "Ghana", phoneCode: "233", continent: "Africa" },
    { name: "Guinea", phoneCode: "224", continent: "Africa" },
    { name: "Guinea-Bissau", phoneCode: "245", continent: "Africa" },
    { name: "Ivory Coast (Côte d'Ivoire)", phoneCode: "225", continent: "Africa" },
    { name: "Kenya", phoneCode: "254", continent: "Africa" },
    { name: "Lesotho", phoneCode: "266", continent: "Africa" },
    { name: "Liberia", phoneCode: "231", continent: "Africa" },
    { name: "Libya", phoneCode: "218", continent: "Africa" },
    { name: "Madagascar", phoneCode: "261", continent: "Africa" },
    { name: "Malawi", phoneCode: "265", continent: "Africa" },
    { name: "Mali", phoneCode: "223", continent: "Africa" },
    { name: "Mauritania", phoneCode: "222", continent: "Africa" },
    { name: "Mauritius", phoneCode: "230", continent: "Africa" },
    { name: "Morocco", phoneCode: "212", continent: "Africa" },
    { name: "Mozambique", phoneCode: "258", continent: "Africa" },
    { name: "Namibia", phoneCode: "264", continent: "Africa" },
    { name: "Niger", phoneCode: "227", continent: "Africa" },
    { name: "Nigeria", phoneCode: "234", continent: "Africa" },
    { name: "Rwanda", phoneCode: "250", continent: "Africa" },
    { name: "Sao Tome and Principe", phoneCode: "239", continent: "Africa" },
    { name: "Senegal", phoneCode: "221", continent: "Africa" },
    { name: "Seychelles", phoneCode: "248", continent: "Africa" },
    { name: "Sierra Leone", phoneCode: "232", continent: "Africa" },
    { name: "Somalia", phoneCode: "252", continent: "Africa" },
    { name: "South Africa", phoneCode: "27", continent: "Africa" },
    { name: "South Sudan", phoneCode: "211", continent: "Africa" },
    { name: "Sudan", phoneCode: "249", continent: "Africa" },
    { name: "Tanzania", phoneCode: "255", continent: "Africa" },
    { name: "Togo", phoneCode: "228", continent: "Africa" },
    { name: "Tunisia", phoneCode: "216", continent: "Africa" },
    { name: "Uganda", phoneCode: "256", continent: "Africa" },
    { name: "Zambia", phoneCode: "260", continent: "Africa" },
    { name: "Zimbabwe", phoneCode: "263", continent: "Africa" },

    // Asia
    { name: "Afghanistan", phoneCode: "93", continent: "Asia" },
    { name: "Armenia", phoneCode: "374", continent: "Asia" },
    { name: "Azerbaijan", phoneCode: "994", continent: "Asia" },
    { name: "Bahrain", phoneCode: "973", continent: "Asia" },
    { name: "Bangladesh", phoneCode: "880", continent: "Asia" },
    { name: "Bhutan", phoneCode: "975", continent: "Asia" },
    { name: "Brunei", phoneCode: "673", continent: "Asia" },
    { name: "Cambodia", phoneCode: "855", continent: "Asia" },
    { name: "China", phoneCode: "86", continent: "Asia" },
    { name: "Cyprus", phoneCode: "357", continent: "Asia" },
    { name: "Georgia", phoneCode: "995", continent: "Asia" },
    { name: "India", phoneCode: "91", continent: "Asia" },
    { name: "Indonesia", phoneCode: "62", continent: "Asia" },
    { name: "Iran", phoneCode: "98", continent: "Asia" },
    { name: "Iraq", phoneCode: "964", continent: "Asia" },
    { name: "Israel", phoneCode: "972", continent: "Asia" },
    { name: "Japan", phoneCode: "81", continent: "Asia" },
    { name: "Jordan", phoneCode: "962", continent: "Asia" },
    { name: "Kazakhstan", phoneCode: "7", continent: "Asia" },
    { name: "North Korea", phoneCode: "850", continent: "Asia" },
    { name: "South Korea", phoneCode: "82", continent: "Asia" },
    { name: "Kuwait", phoneCode: "965", continent: "Asia" },
    { name: "Kyrgyzstan", phoneCode: "996", continent: "Asia" },
    { name: "Laos", phoneCode: "856", continent: "Asia" },
    { name: "Lebanon", phoneCode: "961", continent: "Asia" },
    { name: "Malaysia", phoneCode: "60", continent: "Asia" },
    { name: "Maldives", phoneCode: "960", continent: "Asia" },
    { name: "Mongolia", phoneCode: "976", continent: "Asia" },
    { name: "Myanmar (Burma)", phoneCode: "95", continent: "Asia" },
    { name: "Nepal", phoneCode: "977", continent: "Asia" },
    { name: "Oman", phoneCode: "968", continent: "Asia" },
    { name: "Pakistan", phoneCode: "92", continent: "Asia" },
    { name: "Palestine", phoneCode: "970", continent: "Asia" },
    { name: "Philippines", phoneCode: "63", continent: "Asia" },
    { name: "Qatar", phoneCode: "974", continent: "Asia" },
    { name: "Saudi Arabia", phoneCode: "966", continent: "Asia" },
    { name: "Singapore", phoneCode: "65", continent: "Asia" },
    { name: "Sri Lanka", phoneCode: "94", continent: "Asia" },
    { name: "Syria", phoneCode: "963", continent: "Asia" },
    { name: "Tajikistan", phoneCode: "992", continent: "Asia" },
    { name: "Thailand", phoneCode: "66", continent: "Asia" },
    { name: "Timor-Leste", phoneCode: "670", continent: "Asia" },
    { name: "Turkey", phoneCode: "90", continent: "Asia" },
    { name: "Turkmenistan", phoneCode: "993", continent: "Asia" },
    { name: "United Arab Emirates", phoneCode: "971", continent: "Asia" },
    { name: "Uzbekistan", phoneCode: "998", continent: "Asia" },
    { name: "Vietnam", phoneCode: "84", continent: "Asia" },
    { name: "Yemen", phoneCode: "967", continent: "Asia" },

    // Europe
    { name: "Albania", phoneCode: "355", continent: "Europe" },
    { name: "Andorra", phoneCode: "376", continent: "Europe" },
    { name: "Austria", phoneCode: "43", continent: "Europe" },
    { name: "Belarus", phoneCode: "375", continent: "Europe" },
    { name: "Belgium", phoneCode: "32", continent: "Europe" },
    { name: "Bosnia and Herzegovina", phoneCode: "387", continent: "Europe" },
    { name: "Bulgaria", phoneCode: "359", continent: "Europe" },
    { name: "Croatia", phoneCode: "385", continent: "Europe" },
    { name: "Cyprus", phoneCode: "357", continent: "Europe" },
    { name: "Czech Republic", phoneCode: "420", continent: "Europe" },
    { name: "Denmark", phoneCode: "45", continent: "Europe" },
    { name: "Estonia", phoneCode: "372", continent: "Europe" },
    { name: "Finland", phoneCode: "358", continent: "Europe" },
    { name: "France", phoneCode: "33", continent: "Europe" },
    { name: "Germany", phoneCode: "49", continent: "Europe" },
    { name: "Greece", phoneCode: "30", continent: "Europe" },
    { name: "Hungary", phoneCode: "36", continent: "Europe" },
    { name: "Iceland", phoneCode: "354", continent: "Europe" },
    { name: "Ireland", phoneCode: "353", continent: "Europe" },
    { name: "Italy", phoneCode: "39", continent: "Europe" },
    { name: "Kosovo", phoneCode: "383", continent: "Europe" },
    { name: "Latvia", phoneCode: "371", continent: "Europe" },
    { name: "Liechtenstein", phoneCode: "423", continent: "Europe" },
    { name: "Lithuania", phoneCode: "370", continent: "Europe" },
    { name: "Luxembourg", phoneCode: "352", continent: "Europe" },
    { name: "Malta", phoneCode: "356", continent: "Europe" },
    { name: "Moldova", phoneCode: "373", continent: "Europe" },
    { name: "Monaco", phoneCode: "377", continent: "Europe" },
    { name: "Montenegro", phoneCode: "382", continent: "Europe" },
    { name: "Netherlands", phoneCode: "31", continent: "Europe" },
    { name: "North Macedonia", phoneCode: "389", continent: "Europe" },
    { name: "Norway", phoneCode: "47", continent: "Europe" },
    { name: "Poland", phoneCode: "48", continent: "Europe" },
    { name: "Portugal", phoneCode: "351", continent: "Europe" },
    { name: "Romania", phoneCode: "40", continent: "Europe" },
    { name: "Russia", phoneCode: "7", continent: "Europe" },
    { name: "San Marino", phoneCode: "378", continent: "Europe" },
    { name: "Serbia", phoneCode: "381", continent: "Europe" },
    { name: "Slovakia", phoneCode: "421", continent: "Europe" },
    { name: "Slovenia", phoneCode: "386", continent: "Europe" },
    { name: "Spain", phoneCode: "34", continent: "Europe" },
    { name: "Sweden", phoneCode: "46", continent: "Europe" },
    { name: "Switzerland", phoneCode: "41", continent: "Europe" },
    { name: "Ukraine", phoneCode: "380", continent: "Europe" },
    { name: "United Kingdom", phoneCode: "44", continent: "Europe" },
    { name: "Vatican City", phoneCode: "379", continent: "Europe" },

    // North America
    { name: "Antigua and Barbuda", phoneCode: "1", continent: "North America" },
    { name: "Bahamas", phoneCode: "1", continent: "North America" },
    { name: "Barbados", phoneCode: "1", continent: "North America" },
    { name: "Belize", phoneCode: "501", continent: "North America" },
    { name: "Canada", phoneCode: "1", continent: "North America" },
    { name: "Costa Rica", phoneCode: "506", continent: "North America" },
    { name: "Cuba", phoneCode: "53", continent: "North America" },
    { name: "Dominica", phoneCode: "1", continent: "North America" },
    { name: "Dominican Republic", phoneCode: "1", continent: "North America" },
    { name: "El Salvador", phoneCode: "503", continent: "North America" },
    { name: "Grenada", phoneCode: "1", continent: "North America" },
    { name: "Guatemala", phoneCode: "502", continent: "North America" },
    { name: "Haiti", phoneCode: "509", continent: "North America" },
    { name: "Honduras", phoneCode: "504", continent: "North America" },
    { name: "Jamaica", phoneCode: "1", continent: "North America" },
    { name: "Mexico", phoneCode: "52", continent: "North America" },
    { name: "Nicaragua", phoneCode: "505", continent: "North America" },
    { name: "Panama", phoneCode: "507", continent: "North America" },
    { name: "Saint Kitts and Nevis", phoneCode: "1", continent: "North America" },
    { name: "Saint Lucia", phoneCode: "1", continent: "North America" },
    { name: "Saint Vincent and the Grenadines", phoneCode: "1", continent: "North America" },
    { name: "Trinidad and Tobago", phoneCode: "1", continent: "North America" },
    { name: "United States of America", phoneCode: "1", continent: "North America" },

    // Oceania
    { name: "Australia", phoneCode: "61", continent: "Oceania" },
    { name: "Fiji", phoneCode: "679", continent: "Oceania" },
    { name: "Kiribati", phoneCode: "686", continent: "Oceania" },
    { name: "Marshall Islands", phoneCode: "692", continent: "Oceania" },
    { name: "Micronesia", phoneCode: "691", continent: "Oceania" },
    { name: "Nauru", phoneCode: "674", continent: "Oceania" },
    { name: "New Zealand", phoneCode: "64", continent: "Oceania" },
    { name: "Palau", phoneCode: "680", continent: "Oceania" },
    { name: "Papua New Guinea", phoneCode: "675", continent: "Oceania" },
    { name: "Samoa", phoneCode: "685", continent: "Oceania" },
    { name: "Solomon Islands", phoneCode: "677", continent: "Oceania" },
    { name: "Tonga", phoneCode: "676", continent: "Oceania" },
    { name: "Tuvalu", phoneCode: "688", continent: "Oceania" },
    { name: "Vanuatu", phoneCode: "678", continent: "Oceania" },

    // South America
    { name: "Argentina", phoneCode: "54", continent: "South America" },
    { name: "Bolivia", phoneCode: "591", continent: "South America" },
    { name: "Brazil", phoneCode: "55", continent: "South America" },
    { name: "Chile", phoneCode: "56", continent: "South America" },
    { name: "Colombia", phoneCode: "57", continent: "South America" },
    { name: "Ecuador", phoneCode: "593", continent: "South America" },
    { name: "Guyana", phoneCode: "592", continent: "South America" },
    { name: "Paraguay", phoneCode: "595", continent: "South America" },
    { name: "Peru", phoneCode: "51", continent: "South America" },
    { name: "Suriname", phoneCode: "597", continent: "South America" },
    { name: "Uruguay", phoneCode: "598", continent: "South America" },
    { name: "Venezuela", phoneCode: "58", continent: "South America" },
]

export default countries